In [1]:
import torch
import torch.nn as nn

In [17]:
x = torch.randn(3,2)
print(x)

tensor([[ 1.2343, -1.1428],
        [-1.0701,  0.2306],
        [ 0.4816,  1.2205]])


In [18]:
t = torch.tensor([[0,1],[1,0],[0,1]],dtype=torch.float32)
print(t)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [19]:
y = torch.sigmoid(x)
print(y)

tensor([[0.7746, 0.2418],
        [0.2554, 0.5574],
        [0.6181, 0.7722]])


In [20]:
loss = nn.BCELoss()
print(loss(y,t))

tensor(1.0518)
