In [1]:
import torch
import torch.nn as nn

In [2]:
# 真实值为类别标签
x = torch.randn(6,8)
print(x)

tensor([[-0.0519,  0.7648,  0.2926, -0.1297, -1.3882, -0.4408,  0.8794, -0.4996],
        [-1.6943,  2.1995, -0.5997,  2.7545, -0.4448, -0.5698,  0.3188,  0.0243],
        [ 0.7518,  0.3118,  2.3548,  0.6190, -1.5618, -0.0761,  0.4617, -0.7625],
        [-1.3390,  0.2154, -0.1609,  0.3060, -1.2829,  0.3233, -2.4025,  0.6526],
        [ 0.1053,  0.4047,  0.7887,  0.5437, -0.2777,  1.4144, -1.0145,  0.6834],
        [-2.0725,  0.3548,  0.6574,  0.5259, -0.8719,  0.6562,  0.0587, -0.5493]])


In [3]:
t = torch.tensor([1,0,3,2,5,7])
print(t)

tensor([1, 0, 3, 2, 5, 7])


In [4]:
loss = nn.CrossEntropyLoss()
print(loss(x,t))

tensor(2.4968)


In [5]:
t = torch.randn(6,8).softmax(dim=1)
print(t)

tensor([[0.1234, 0.0689, 0.0346, 0.0499, 0.3289, 0.2063, 0.1427, 0.0453],
        [0.0051, 0.1160, 0.1514, 0.0811, 0.0735, 0.0253, 0.5365, 0.0111],
        [0.0324, 0.0122, 0.0759, 0.0662, 0.6304, 0.0567, 0.0841, 0.0419],
        [0.0260, 0.0797, 0.0527, 0.0400, 0.1644, 0.4932, 0.0525, 0.0915],
        [0.0038, 0.1160, 0.0682, 0.3812, 0.0212, 0.0869, 0.1407, 0.1821],
        [0.0475, 0.4923, 0.0802, 0.0572, 0.0079, 0.0987, 0.0695, 0.1468]])


In [6]:
print(loss(x,t))

tensor(2.5973)


In [12]:
input = torch.randn(6,8)
print(input)
target = torch.randint(8,(6,))
print(target)

tensor([[-1.1430, -0.0423, -0.2064,  0.3304, -0.9084,  0.2285, -1.8029, -1.3991],
        [ 0.6710,  1.7226,  1.0864, -0.3117,  1.1142,  0.6946, -0.6056, -0.2967],
        [-1.1369,  0.2617, -0.6408,  0.7530, -0.0324,  1.3238, -0.6463, -0.7071],
        [-1.3182,  0.8149, -0.3991,  0.2470,  0.3224,  0.3263, -0.6876, -0.2677],
        [-0.6128, -0.2937,  0.1444, -1.2280, -1.0117,  0.6214,  1.2100,  0.3226],
        [-0.6424,  0.2140,  0.1141,  0.2005,  0.7151,  0.3913, -0.1709, -0.8651]])
tensor([0, 4, 0, 4, 1, 6])


In [13]:
loss = nn.CrossEntropyLoss()
print(loss(input,target))

tensor(2.4654)


In [14]:
loss1 = nn.LogSoftmax(dim=1)
y = loss1(input)
loss2 = nn.NLLLoss()
print(loss2(y,target))

tensor(2.4654)
