In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x = torch.randn(1, 3, 2, 4)
x,x.shape

(tensor([[[[ 1.2116,  0.9539,  3.0147, -1.4955],
           [ 1.4230, -1.1373, -0.9197, -0.2280]],
 
          [[-0.5065,  0.0453, -0.4598,  0.2603],
           [-0.6612,  0.2447,  1.9967,  0.5269]],
 
          [[ 0.2983, -2.3495,  0.8167,  1.1834],
           [-0.5090, -0.6303,  0.5588, -0.3302]]]]),
 torch.Size([1, 3, 2, 4]))

In [6]:
x = x[:,:,:,None,:].expand(1,3,2,2,4)
x,x.shape

(tensor([[[[[ 1.2116,  0.9539,  3.0147, -1.4955],
            [ 1.2116,  0.9539,  3.0147, -1.4955]],
 
           [[ 1.4230, -1.1373, -0.9197, -0.2280],
            [ 1.4230, -1.1373, -0.9197, -0.2280]]],
 
 
          [[[-0.5065,  0.0453, -0.4598,  0.2603],
            [-0.5065,  0.0453, -0.4598,  0.2603]],
 
           [[-0.6612,  0.2447,  1.9967,  0.5269],
            [-0.6612,  0.2447,  1.9967,  0.5269]]],
 
 
          [[[ 0.2983, -2.3495,  0.8167,  1.1834],
            [ 0.2983, -2.3495,  0.8167,  1.1834]],
 
           [[-0.5090, -0.6303,  0.5588, -0.3302],
            [-0.5090, -0.6303,  0.5588, -0.3302]]]]]),
 torch.Size([1, 3, 2, 2, 4]))

In [7]:
x= x.reshape(1,3,4,4)
x,x.shape

(tensor([[[[ 1.2116,  0.9539,  3.0147, -1.4955],
           [ 1.2116,  0.9539,  3.0147, -1.4955],
           [ 1.4230, -1.1373, -0.9197, -0.2280],
           [ 1.4230, -1.1373, -0.9197, -0.2280]],
 
          [[-0.5065,  0.0453, -0.4598,  0.2603],
           [-0.5065,  0.0453, -0.4598,  0.2603],
           [-0.6612,  0.2447,  1.9967,  0.5269],
           [-0.6612,  0.2447,  1.9967,  0.5269]],
 
          [[ 0.2983, -2.3495,  0.8167,  1.1834],
           [ 0.2983, -2.3495,  0.8167,  1.1834],
           [-0.5090, -0.6303,  0.5588, -0.3302],
           [-0.5090, -0.6303,  0.5588, -0.3302]]]]),
 torch.Size([1, 3, 4, 4]))

In [8]:
mask = torch.full((1, 1, 4, 4), float("-inf"))
mask,mask.shape

(tensor([[[[-inf, -inf, -inf, -inf],
           [-inf, -inf, -inf, -inf],
           [-inf, -inf, -inf, -inf],
           [-inf, -inf, -inf, -inf]]]]),
 torch.Size([1, 1, 4, 4]))

In [9]:
mask = torch.triu(mask, diagonal=1)
mask.shape,mask

(torch.Size([1, 1, 4, 4]),
 tensor([[[[0., -inf, -inf, -inf],
           [0., 0., -inf, -inf],
           [0., 0., 0., -inf],
           [0., 0., 0., 0.]]]]))