In [1]:
import torch
import numpy as np

In [2]:
# 1.基本张量创建，
# 创建标量
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [6]:
# 传入列表
tensor2 = torch.tensor([1, 2, 3, 4, 5])
tensor3 = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(tensor2)
print(tensor3)
print(tensor2.shape)
print(tensor3.shape)

tensor([1, 2, 3, 4, 5])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
torch.Size([5])
torch.Size([2, 5])


In [12]:
# 传入ndarray
tensor4 = torch.tensor(np.array([[1.0, 2, 3, 4, 5], [6, 7, 8, 9, 10]]))
print(tensor4)
print(tensor4.dtype)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]], dtype=torch.float64)
torch.float64


In [16]:
tensor5 = torch.Tensor(np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]))
print(tensor5)
print(tensor5.dtype)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
torch.float32


In [17]:
tensor6 = torch.tensor(np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]), dtype=torch.int32)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]], dtype=torch.int32)
torch.int32


In [23]:
tensor = torch.arange(10, 30, 2)
print(tensor)
print(tensor.dtype)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
torch.int64


In [27]:
tensor = torch.arange(10)
print(tensor)
print(tensor.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


In [28]:
tensor = torch.linspace(10, 30, 5)
print(tensor)
print(tensor.dtype)

tensor([10., 15., 20., 25., 30.])
torch.float32


In [38]:
tensor = torch.logspace(1, 3, 3, 2)
print(tensor)
print(tensor.dtype)

tensor([2., 4., 8.])
torch.float32


In [48]:
tensor = torch.zeros(2, 3)
tensor1 = torch.ones_like(tensor)
print(tensor, tensor.dtype)
print(tensor1, tensor1.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32


In [51]:
tensor = torch.full((2,3),5.0)
print(tensor,tensor.dtype)

tensor([[5., 5., 5.],
        [5., 5., 5.]]) torch.float32


In [57]:
tensor = torch.empty(3,2,2)
print(tensor,tensor.dtype)

tensor([[[2.3301e-09, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[1.0051e-12, 0.0000e+00],
         [1.0842e-19, 0.0000e+00]],

        [[0.0000e+00, 1.8750e+00],
         [0.0000e+00, 1.8750e+00]]]) torch.float32


In [59]:
tensor = torch.eye(3)
tensor1 = torch.eye(3,4)
print(tensor,tensor.dtype)
print(tensor1,tensor1.dtype)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) torch.float32
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]) torch.float32


In [64]:
# 随机张量创建
# [0，1] 均匀分布
tensor = torch.rand((2,3))
print(tensor,tensor.dtype)

tensor([[0.1447, 0.2796, 0.1470],
        [0.7652, 0.9877, 0.0258]]) torch.float32


In [71]:
tensor = torch.randint(1,10,(2,3))
print(tensor,tensor.dtype)

tensor([[6, 1, 6],
        [9, 2, 6]]) torch.int64


In [66]:
tensor = torch.randn((2,3))
print(tensor,tensor.dtype)

tensor([[-0.1970,  0.7301,  0.2123],
        [ 0.5579,  0.8457, -0.6637]]) torch.float32


In [75]:
tensor = torch.normal(5,2,(2,3))
print(tensor,tensor.dtype)

tensor([[3.6558, 7.0902, 4.6020],
        [5.1070, 1.1592, 4.0834]]) torch.float32


In [76]:
# torch.randperm(n) 生成从0到n-1的随机排列
tensor1 = torch.randperm(10)
print(tensor1)


tensor([9, 3, 8, 4, 2, 0, 7, 5, 6, 1])


In [81]:
print(torch.random.initial_seed())
torch.manual_seed(42)

42
42


In [ ]:
# 张量类型