In [1]:
import torch
import numpy as np

In [9]:
tensor = torch.tensor([1, 2, 3])
print(tensor,tensor.dtype)
tensor = tensor.type(torch.float64)
print(tensor,tensor.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.], dtype=torch.float64) torch.float64


In [10]:
tensor = torch.Tensor( 2, 3)
print(tensor,tensor.dtype)

tensor([[6.7999e-14, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]]) torch.float32


In [13]:
# tensor 和 ndarray的转换
tensor = torch.rand(3,2)
print(tensor,tensor.dtype)
np_array = tensor.numpy()  # 共享内存
print(np_array,np_array.dtype)
print(type(tensor),type(np_array))

tensor([[0.3238, 0.8389],
        [0.6180, 0.5156],
        [0.4881, 0.0580]]) torch.float32
[[0.32377404 0.83892065]
 [0.6180481  0.51556236]
 [0.48808485 0.05796635]] float32
<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [16]:
tensor[:,0] = 10
print(tensor,tensor.dtype)
print(np_array,np_array.dtype)
print(id(tensor),id(np_array))

tensor([[10.0000,  0.8389],
        [10.0000,  0.5156],
        [10.0000,  0.0580]]) torch.float32
[[10.          0.83892065]
 [10.          0.51556236]
 [10.          0.05796635]] float32
138119447331920 138119450111376


In [18]:
np_array2 = tensor.numpy().copy()
tensor[:,0] = 11
print(tensor)
print(np_array2)

tensor([[11.0000,  0.8389],
        [11.0000,  0.5156],
        [11.0000,  0.0580]])
[[11.          0.83892065]
 [11.          0.51556236]
 [11.          0.05796635]]


In [20]:
# 将ndarray 转化为 tensor
np_array = np.random.randn(3,2)
tensor = torch.from_numpy(np_array)
print(np_array,np_array.dtype)
print(tensor,tensor.dtype)

[[-0.01463454 -0.3218049 ]
 [ 0.35958845  0.88864921]
 [-0.15374413  1.32742366]] float64
tensor([[-0.0146, -0.3218],
        [ 0.3596,  0.8886],
        [-0.1537,  1.3274]], dtype=torch.float64) torch.float64


In [22]:
tensor1 = torch.tensor(np_array)
print(tensor1,tensor1.dtype)

tensor([[-0.0146, -0.3218],
        [ 0.3596,  0.8886],
        [-0.1537,  1.3274]]) torch.float32


In [24]:
tensor2 = torch.tensor([[1]])
print(tensor2)
print(tensor2.item())

tensor([[1]])
1
