In [2]:
import torch


In [6]:

tensor1 = torch.randint(1, 9, (2, 3))
print(tensor1)
print(tensor1 + 10)
print(tensor1)
print("*" * 100)

# add()，不修改原数据
print(tensor1.add(10))
print(tensor1)
print("*" * 100)

# add_() 修改原数据
print(tensor1.add_(10))
print(tensor1)
print("*" * 100)


tensor([[5, 8, 7],
        [6, 8, 8]])
tensor([[15, 18, 17],
        [16, 18, 18]])
tensor([[5, 8, 7],
        [6, 8, 8]])
****************************************************************************************************
tensor([[15, 18, 17],
        [16, 18, 18]])
tensor([[5, 8, 7],
        [6, 8, 8]])
****************************************************************************************************
tensor([[15, 18, 17],
        [16, 18, 18]])
tensor([[15, 18, 17],
        [16, 18, 18]])
****************************************************************************************************


In [10]:
print(-tensor1)
print(tensor1)
print("*" * 100)
#
print(tensor1.neg())
print(tensor1)
print("*" * 100)

print(tensor1.neg_())
print(tensor1)
print("*" * 100)


tensor([[15, 18, 17],
        [16, 18, 18]])
tensor([[-15, -18, -17],
        [-16, -18, -18]])
****************************************************************************************************
tensor([[15, 18, 17],
        [16, 18, 18]])
tensor([[-15, -18, -17],
        [-16, -18, -18]])
****************************************************************************************************
tensor([[15, 18, 17],
        [16, 18, 18]])
tensor([[15, 18, 17],
        [16, 18, 18]])
****************************************************************************************************


In [11]:
print(tensor1.type(torch.float).sqrt_())
print(tensor1)
print("*" * 100)

tensor([[3.8730, 4.2426, 4.1231],
        [4.0000, 4.2426, 4.2426]])
tensor([[15, 18, 17],
        [16, 18, 18]])
****************************************************************************************************


In [14]:
# 哈达玛积（元素级乘法）使用*、mul()实现两个形状相同的张量之间对位相乘
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[1, 2], [3, 4]])
print(tensor1 * tensor2)
print(tensor1 + tensor2)
print(tensor1.mul(tensor2))


tensor([[ 1,  4],
        [ 9, 16]])
tensor([[2, 4],
        [6, 8]])
tensor([[ 1,  4],
        [ 9, 16]])


In [16]:
# 维矩阵的矩阵乘法
# mm() 严格用于二维矩阵相乘
# @ 、 matmul() 支持多维张量，按最后两个维度做矩阵乘法，其他维度广播
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(tensor1)
print(tensor2)
print(tensor1.mm(tensor2))
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))
print()


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])



In [23]:
tensor1 = torch.tensor([[[1, 2, 3], [4, 5, 6]],[[4, 5, 6],[1, 2, 3]]])
print(tensor1.shape)
tensor2 = torch.tensor([[[1, 2], [3, 4], [5, 6]]])
print(tensor2.shape)
t = tensor1 @ tensor2
print(t.shape)
print(t)


torch.Size([2, 2, 3])
torch.Size([1, 3, 2])
torch.Size([2, 2, 2])
tensor([[[22, 28],
         [49, 64]],

        [[49, 64],
         [22, 28]]])


In [24]:
# 内积运算 dot 必须是一维向量相乘
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
print(tensor1.dot(tensor2))



tensor(32)


In [26]:
X = torch.randint(1, 9, (3, 2, 4))
Y = torch.randint(1, 9, (3, 2, 4))
print(id(X))
X[:] = X * Y
print(id(X), end="\n\n")


124442597059104
124442597059104



In [37]:
X = torch.randint(1, 9, (3, 2, 4))
Y = torch.randint(1, 9, (3, 4, 1))
print(id(X))
X[:] = X @ Y
print(id(X), end="\n\n")
print(X.shape)

124442586155424
124442586155424

torch.Size([3, 2, 4])


In [3]:
tensor = torch.randint(1, 9, (3, 2, 4))
print(tensor)

tensor([[[4, 3, 8, 8],
         [5, 7, 7, 8]],

        [[7, 4, 3, 2],
         [8, 7, 6, 7]],

        [[1, 4, 4, 6],
         [8, 2, 2, 8]]])


In [6]:
s = tensor.sum(dim=0)
print(s)
print(s.shape)

tensor([[12, 11, 15, 16],
        [21, 16, 15, 23]])
torch.Size([2, 4])
