In [1]:
import torch

In [14]:
tensor = torch.randint(1, 10, (3, 2, 4))
print(tensor)

tensor([[[3, 8, 3, 3],
         [4, 3, 1, 2]],

        [[4, 6, 4, 6],
         [2, 5, 6, 9]],

        [[6, 2, 5, 7],
         [6, 3, 6, 6]]])


In [8]:
s = tensor.sum()
print(s)
print(s.shape)

tensor(146)
torch.Size([])


In [9]:
s = tensor.sum(dim=0)
print(s)
print(s.shape)

tensor([[15, 17, 19, 15],
        [19, 16, 22, 23]])
torch.Size([2, 4])


In [10]:
s = tensor.sum(dim=1)
print(s)
print(s.shape)

tensor([[ 6,  9, 17, 13],
        [14, 10, 10, 13],
        [14, 14, 14, 12]])
torch.Size([3, 4])


In [12]:
s = tensor.sum(dim=2)
print(s)
print(s.shape)

tensor([[22, 23],
        [19, 28],
        [25, 29]])
torch.Size([3, 2])


In [20]:
tensor = torch.randint(1, 10, (3, 2, 4),dtype=torch.float)
print(tensor)
print(tensor.mean())
print(tensor.std())

tensor([[[3., 5., 4., 4.],
         [2., 9., 5., 2.]],

        [[2., 5., 3., 5.],
         [1., 9., 3., 2.]],

        [[1., 5., 6., 9.],
         [2., 1., 4., 4.]]])
tensor(4.)
tensor(2.4137)


In [31]:
print(tensor.mean(dim=0))

tensor([[2.0000, 5.0000, 4.3333, 6.0000],
        [1.6667, 6.3333, 4.0000, 2.6667]])


In [28]:
print(tensor.argmax(dim=1))

tensor([[0, 1, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]])


In [27]:
print(tensor.unique(dim=1))

tensor([[[2., 9., 5., 2.],
         [3., 5., 4., 4.]],

        [[1., 9., 3., 2.],
         [2., 5., 3., 5.]],

        [[2., 1., 4., 4.],
         [1., 5., 6., 9.]]])


In [32]:
print(tensor.sort())

torch.return_types.sort(
values=tensor([[[3., 4., 4., 5.],
         [2., 2., 5., 9.]],

        [[2., 3., 5., 5.],
         [1., 2., 3., 9.]],

        [[1., 5., 6., 9.],
         [1., 2., 4., 4.]]]),
indices=tensor([[[0, 2, 3, 1],
         [0, 3, 2, 1]],

        [[0, 2, 1, 3],
         [0, 3, 2, 1]],

        [[0, 1, 2, 3],
         [1, 0, 2, 3]]]))
