In [1]:
import torch

In [7]:
tensor = torch.randint(0,10,(3,5,4))
print(tensor)

tensor([[[7, 0, 7, 9],
         [6, 8, 7, 2],
         [9, 4, 5, 0],
         [1, 1, 5, 9],
         [2, 1, 7, 2]],

        [[6, 7, 1, 3],
         [7, 6, 3, 0],
         [6, 4, 4, 9],
         [8, 5, 8, 5],
         [4, 2, 3, 9]],

        [[6, 8, 5, 9],
         [9, 6, 7, 9],
         [1, 5, 2, 8],
         [0, 3, 1, 6],
         [8, 8, 6, 6]]])


In [8]:
print(tensor[0])
print(tensor[0,1,1])

tensor([[7, 0, 7, 9],
        [6, 8, 7, 2],
        [9, 4, 5, 0],
        [1, 1, 5, 9],
        [2, 1, 7, 2]])
tensor(8)


In [9]:
# 取所有矩阵第二行
print(tensor[:,1])

tensor([[6, 8, 7, 2],
        [7, 6, 3, 0],
        [9, 6, 7, 9]])


In [6]:
# 范围索引
print(tensor[1:])

tensor([[[1, 1, 2, 9],
         [4, 1, 3, 9]],

        [[4, 6, 6, 1],
         [9, 0, 8, 9]]])


In [13]:
print(tensor[-1,1:4,0:3])
print(tensor)

tensor([[9, 6, 7],
        [1, 5, 2],
        [0, 3, 1]])
tensor([[[7, 0, 7, 9],
         [6, 8, 7, 2],
         [9, 4, 5, 0],
         [1, 1, 5, 9],
         [2, 1, 7, 2]],

        [[6, 7, 1, 3],
         [7, 6, 3, 0],
         [6, 4, 4, 9],
         [8, 5, 8, 5],
         [4, 2, 3, 9]],

        [[6, 8, 5, 9],
         [9, 6, 7, 9],
         [1, 5, 2, 8],
         [0, 3, 1, 6],
         [8, 8, 6, 6]]])


In [14]:
print(tensor[[[0],[1]],[1,2]])

tensor([[[6, 8, 7, 2],
         [9, 4, 5, 0]],

        [[7, 6, 3, 0],
         [6, 4, 4, 9]]])


In [16]:
mask = tensor > 5
print(mask)
print(tensor[mask])

tensor([[[ True, False,  True,  True],
         [ True,  True,  True, False],
         [ True, False, False, False],
         [False, False, False,  True],
         [False, False,  True, False]],

        [[ True,  True, False, False],
         [ True,  True, False, False],
         [ True, False, False,  True],
         [ True, False,  True, False],
         [False, False, False,  True]],

        [[ True,  True, False,  True],
         [ True,  True,  True,  True],
         [False, False, False,  True],
         [False, False, False,  True],
         [ True,  True,  True,  True]]])
tensor([7, 7, 9, 6, 8, 7, 9, 9, 7, 6, 7, 7, 6, 6, 9, 8, 8, 9, 6, 8, 9, 9, 6, 7,
        9, 8, 6, 8, 8, 6, 6])


In [23]:
# 选取首元素大于5的所有行
mask = tensor[:,:,0] > 5
print(mask)
print(tensor[mask].shape)

tensor([[ True,  True,  True, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True, False, False,  True]])
torch.Size([10, 4])


In [28]:
# 选取第二个元素大于5的所有列
mask = tensor[:,1,:] > 5
print(mask)
tensor2 = tensor.permute(0,2,1)
print(tensor2)
print(tensor2.shape)
result = tensor2[mask]
print(result)
print(result.T)

tensor([[ True,  True,  True, False],
        [ True,  True, False, False],
        [ True,  True,  True,  True]])
tensor([[[7, 6, 9, 1, 2],
         [0, 8, 4, 1, 1],
         [7, 7, 5, 5, 7],
         [9, 2, 0, 9, 2]],

        [[6, 7, 6, 8, 4],
         [7, 6, 4, 5, 2],
         [1, 3, 4, 8, 3],
         [3, 0, 9, 5, 9]],

        [[6, 9, 1, 0, 8],
         [8, 6, 5, 3, 8],
         [5, 7, 2, 1, 6],
         [9, 9, 8, 6, 6]]])
torch.Size([3, 4, 5])
tensor([[7, 6, 9, 1, 2],
        [0, 8, 4, 1, 1],
        [7, 7, 5, 5, 7],
        [6, 7, 6, 8, 4],
        [7, 6, 4, 5, 2],
        [6, 9, 1, 0, 8],
        [8, 6, 5, 3, 8],
        [5, 7, 2, 1, 6],
        [9, 9, 8, 6, 6]])
tensor([[7, 0, 7, 6, 7, 6, 8, 5, 9],
        [6, 8, 7, 7, 6, 9, 6, 7, 9],
        [9, 4, 5, 6, 4, 1, 5, 2, 8],
        [1, 1, 5, 8, 5, 0, 3, 1, 6],
        [2, 1, 7, 4, 2, 8, 8, 6, 6]])


In [31]:
# 选取矩阵
mask = tensor[:,1,2] > 5
print(mask)
print(tensor[mask])

tensor([ True, False,  True])
tensor([[[7, 0, 7, 9],
         [6, 8, 7, 2],
         [9, 4, 5, 0],
         [1, 1, 5, 9],
         [2, 1, 7, 2]],

        [[6, 8, 5, 9],
         [9, 6, 7, 9],
         [1, 5, 2, 8],
         [0, 3, 1, 6],
         [8, 8, 6, 6]]])
