In [1]:
import torch

In [2]:
# 交换维度
tensor = torch.randint(0,10,(3,2,5))
print(tensor)

tensor([[[5, 5, 0, 5, 6],
         [0, 6, 8, 8, 2]],

        [[3, 1, 1, 1, 2],
         [1, 2, 2, 7, 8]],

        [[3, 6, 5, 3, 9],
         [4, 2, 2, 5, 3]]])


In [4]:
# 交换两个维度
print(tensor.transpose(-1,-2))

tensor([[[5, 0],
         [5, 6],
         [0, 8],
         [5, 8],
         [6, 2]],

        [[3, 1],
         [1, 2],
         [1, 2],
         [1, 7],
         [2, 8]],

        [[3, 4],
         [6, 2],
         [5, 2],
         [3, 5],
         [9, 3]]])


In [5]:
print(tensor.transpose(0,2))

tensor([[[5, 3, 3],
         [0, 1, 4]],

        [[5, 1, 6],
         [6, 2, 2]],

        [[0, 1, 5],
         [8, 2, 2]],

        [[5, 1, 3],
         [8, 7, 5]],

        [[6, 2, 9],
         [2, 8, 3]]])


In [6]:
# 重新排列所有维度
print(tensor.permute(0,2,1))

tensor([[[5, 0],
         [5, 6],
         [0, 8],
         [5, 8],
         [6, 2]],

        [[3, 1],
         [1, 2],
         [1, 2],
         [1, 7],
         [2, 8]],

        [[3, 4],
         [6, 2],
         [5, 2],
         [3, 5],
         [9, 3]]])


In [10]:
# 调整形状
print(tensor.reshape(3,-1))

tensor([[5, 5, 0, 5, 6, 0, 6, 8, 8, 2],
        [3, 1, 1, 1, 2, 1, 2, 2, 7, 8],
        [3, 6, 5, 3, 9, 4, 2, 2, 5, 3]])


In [11]:
# view 必须在连续内存操作
print(tensor.contiguous().view(3,-1))

tensor([[5, 5, 0, 5, 6, 0, 6, 8, 8, 2],
        [3, 1, 1, 1, 2, 1, 2, 2, 7, 8],
        [3, 6, 5, 3, 9, 4, 2, 2, 5, 3]])


In [14]:
tensor = tensor.T
print(tensor.T)
print(tensor.is_contiguous())

tensor([[[5, 5, 0, 5, 6],
         [0, 6, 8, 8, 2]],

        [[3, 1, 1, 1, 2],
         [1, 2, 2, 7, 8]],

        [[3, 6, 5, 3, 9],
         [4, 2, 2, 5, 3]]])
False


In [16]:
print(tensor.contiguous().view(-1,2))

tensor([[5, 3],
        [3, 0],
        [1, 4],
        [5, 1],
        [6, 6],
        [2, 2],
        [0, 1],
        [5, 8],
        [2, 2],
        [5, 1],
        [3, 8],
        [7, 5],
        [6, 2],
        [9, 2],
        [8, 3]])


In [20]:
# 增加或删除维度
tensor1 = torch.tensor([1,2,3,4,5])
print(tensor1,tensor1.shape)
print(tensor1.unsqueeze(0),tensor1.unsqueeze(0).shape)
print(tensor1.unsqueeze(1),tensor1.unsqueeze(1).shape)

tensor([1, 2, 3, 4, 5]) torch.Size([5])
tensor([[1, 2, 3, 4, 5]]) torch.Size([1, 5])
tensor([[1],
        [2],
        [3],
        [4],
        [5]]) torch.Size([5, 1])


In [22]:
# 删除维度，只能删除大小为1的维度
tensor2 = torch.randint(0,10,(3,1,5))
print(tensor2,tensor2.shape)
print(tensor2.squeeze(1),tensor2.squeeze(1).shape)

tensor([[[3, 1, 4, 5, 9]],

        [[9, 6, 8, 5, 3]],

        [[2, 0, 5, 7, 2]]]) torch.Size([3, 1, 5])
tensor([[3, 1, 4, 5, 9],
        [9, 6, 8, 5, 3],
        [2, 0, 5, 7, 2]]) torch.Size([3, 5])


In [23]:
# 张量拼接,除拼接维度其他维度必须相同
tensor1 = torch.randint(0,10,(3,2,5))
tensor2 = torch.randint(0,10,(3,1,5))
print(tensor1,tensor1.shape)
print(tensor2,tensor2.shape)

tensor([[[3, 0, 2, 7, 8],
         [4, 6, 7, 6, 5]],

        [[7, 4, 3, 7, 6],
         [9, 2, 1, 1, 4]],

        [[1, 8, 8, 0, 9],
         [4, 9, 8, 6, 8]]]) torch.Size([3, 2, 5])
tensor([[[6, 2, 7, 7, 7]],

        [[3, 4, 8, 1, 1]],

        [[0, 4, 9, 2, 5]]]) torch.Size([3, 1, 5])


In [24]:
print(torch.cat((tensor1,tensor2),dim=1))

tensor([[[3, 0, 2, 7, 8],
         [4, 6, 7, 6, 5],
         [6, 2, 7, 7, 7]],

        [[7, 4, 3, 7, 6],
         [9, 2, 1, 1, 4],
         [3, 4, 8, 1, 1]],

        [[1, 8, 8, 0, 9],
         [4, 9, 8, 6, 8],
         [0, 4, 9, 2, 5]]])


In [27]:
# 张量堆叠，按新维度堆叠。所有张量形状必须一致
tensor1 = torch.randint(0,10,(3,1,5))
tensor2 = torch.randint(0,10,(3,1,5))
print(tensor1)
print(tensor2)

tensor([[[7, 9, 7, 9, 3]],

        [[7, 8, 9, 1, 7]],

        [[3, 6, 6, 1, 7]]])
tensor([[[5, 6, 7, 5, 3]],

        [[8, 0, 8, 2, 4]],

        [[1, 9, 6, 8, 9]]])


In [35]:
t3 = torch.stack([tensor1,tensor2],dim=1)
print(t3.squeeze(2))
print(t3.squeeze(2).shape)

tensor([[[7, 9, 7, 9, 3],
         [5, 6, 7, 5, 3]],

        [[7, 8, 9, 1, 7],
         [8, 0, 8, 2, 4]],

        [[3, 6, 6, 1, 7],
         [1, 9, 6, 8, 9]]])
torch.Size([3, 2, 5])
