In [20]:
import torch

In [26]:
# 定义输入数据x和标签y
x = torch.tensor(10.0,requires_grad=True)
print(x)
y = torch.tensor([[3.0]])

tensor(10., requires_grad=True)


In [27]:
w = torch.rand(1,1,requires_grad=True)
print(w)
b = torch.rand(1,1,requires_grad=True)
print(b)

tensor([[0.6560]], requires_grad=True)
tensor([[0.7400]], requires_grad=True)


In [28]:
z = w * x + b
print(z)

tensor([[7.2999]], grad_fn=<AddBackward0>)


In [29]:
loss = torch.nn.MSELoss()
loss_value = loss(z,y)
print(loss_value)

tensor(18.4892, grad_fn=<MseLossBackward0>)


In [30]:
# 反向传播
loss_value.backward()
# 打印w,b的梯度
print("w的梯度:\n", w.grad)
print("b的梯度:\n", b.grad)
print("x的梯度:\n", x.grad)


w的梯度:
 tensor([[85.9982]])
b的梯度:
 tensor([[8.5998]])
x的梯度:
 tensor(5.6414)


In [39]:
print(x.is_leaf)  # True
print(w.is_leaf)  # True
print(b.is_leaf)  # True
print(z.is_leaf)  # False
print(y.is_leaf)  # True
print(loss_value.is_leaf)  # False
print(z.retain_grad)

True
True
True
False
True
False
<built-in method retain_grad of Tensor object at 0x305479a80>
