In [1]:
import torch

In [2]:
x = torch.tensor([1.0, 2, 3], requires_grad=True)
y = x.detach()
print(x)
print(y)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.])


In [3]:
print(x.storage().data_ptr())
print(y.storage().data_ptr())

674325824
674325824


/tmp/ipykernel_1902580/1350527349.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(x.storage().data_ptr())


In [4]:
z1 = x ** 2
print(z1)
z2 = y ** 2
print(z2)

tensor([1., 4., 9.], grad_fn=<PowBackward0>)
tensor([1., 4., 9.])


In [5]:
z1.sum().backward()
print(x.grad)

tensor([2., 4., 6.])


In [7]:
x = torch.ones(2,2,requires_grad=True)
print(x)
y = x * x
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [8]:
u = y.detach()
print(u)

tensor([[1., 1.],
        [1., 1.]])


In [9]:
z = u * x
print(z)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [10]:
z.sum().backward()
print(x.grad)
print(u.grad)

tensor([[1., 1.],
        [1., 1.]])
None
