In [1]:
import torch
import torch.nn.functional as F

In [6]:
input = torch.tensor([1, 2, 4, 5])
print(input)

tensor([1, 2, 4, 5])


In [9]:
embedding_matrix = torch.rand(10, 5)
print(embedding_matrix)

tensor([[0.0912, 0.1341, 0.9783, 0.3969, 0.7494],
        [0.8093, 0.9033, 0.6525, 0.1428, 0.4108],
        [0.5197, 0.7564, 0.1403, 0.3182, 0.4999],
        [0.7233, 0.5544, 0.3165, 0.3851, 0.8643],
        [0.9165, 0.4910, 0.1502, 0.3187, 0.7640],
        [0.4307, 0.2520, 0.3692, 0.6025, 0.6987],
        [0.3467, 0.7403, 0.4470, 0.4605, 0.4010],
        [0.4169, 0.1179, 0.5758, 0.4207, 0.1724],
        [0.7006, 0.3475, 0.1625, 0.6716, 0.3205],
        [0.1631, 0.0638, 0.5662, 0.4105, 0.1039]])


In [10]:
out = F.embedding(input, embedding_matrix)
print(out)

tensor([[0.8093, 0.9033, 0.6525, 0.1428, 0.4108],
        [0.5197, 0.7564, 0.1403, 0.3182, 0.4999],
        [0.9165, 0.4910, 0.1502, 0.3187, 0.7640],
        [0.4307, 0.2520, 0.3692, 0.6025, 0.6987]])


In [16]:

for i in range(0,100-10):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
