In [1]:
import torch
import torch.nn.functional as F

In [6]:
input = torch.tensor([1, 2, 4, 5])
print(input)

tensor([1, 2, 4, 5])


In [9]:
embedding_matrix = torch.rand(10, 5)
print(embedding_matrix)

tensor([[0.0912, 0.1341, 0.9783, 0.3969, 0.7494],
        [0.8093, 0.9033, 0.6525, 0.1428, 0.4108],
        [0.5197, 0.7564, 0.1403, 0.3182, 0.4999],
        [0.7233, 0.5544, 0.3165, 0.3851, 0.8643],
        [0.9165, 0.4910, 0.1502, 0.3187, 0.7640],
        [0.4307, 0.2520, 0.3692, 0.6025, 0.6987],
        [0.3467, 0.7403, 0.4470, 0.4605, 0.4010],
        [0.4169, 0.1179, 0.5758, 0.4207, 0.1724],
        [0.7006, 0.3475, 0.1625, 0.6716, 0.3205],
        [0.1631, 0.0638, 0.5662, 0.4105, 0.1039]])


In [10]:
out = F.embedding(input, embedding_matrix)
print(out)

tensor([[0.8093, 0.9033, 0.6525, 0.1428, 0.4108],
        [0.5197, 0.7564, 0.1403, 0.3182, 0.4999],
        [0.9165, 0.4910, 0.1502, 0.3187, 0.7640],
        [0.4307, 0.2520, 0.3692, 0.6025, 0.6987]])
