In [1]:
import torch

In [15]:
x1 = torch.tensor([1., 2, 3,4],requires_grad=True)
x2 = torch.tensor([1., 2, 3,4],requires_grad=True)
print(x1)
print(x2)

tensor([1., 2., 3., 4.], requires_grad=True)
tensor([1., 2., 3., 4.], requires_grad=True)


In [16]:
y1 = x1.sigmoid()
y2 = x2.sigmoid()
print(y1)
print(y2)

tensor([0.7311, 0.8808, 0.9526, 0.9820], grad_fn=<SigmoidBackward0>)
tensor([0.7311, 0.8808, 0.9526, 0.9820], grad_fn=<SigmoidBackward0>)


tensor([0.1966, 0.1050, 0.0452, 0.0177])
tensor([0.1966, 0.1050, 0.0452, 0.0177])


In [17]:
z1 = y1.data
z2 = y2.detach()
print(z1,z1.requires_grad)
print(z2,z2.requires_grad)
print(y1.requires_grad,y2.requires_grad)

tensor([0.7311, 0.8808, 0.9526, 0.9820]) False
tensor([0.7311, 0.8808, 0.9526, 0.9820]) False
True True


In [18]:
z1.zero_()
z2.zero_()
print(y1)
print(y2)

tensor([0., 0., 0., 0.], grad_fn=<SigmoidBackward0>)
tensor([0., 0., 0., 0.], grad_fn=<SigmoidBackward0>)


In [19]:
y1.sum().backward()
print(x1.grad)



tensor([0., 0., 0., 0.])


In [20]:
y2.sum().backward()
print(x2.grad)

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [4]], which is output 0 of SigmoidBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).