In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
# 初始化门控权重
weight = nn.Parameter(torch.empty((4, 10)))
weight,weight.shape

(Parameter containing:
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], requires_grad=True),
 torch.Size([4, 10]))

In [6]:
# 模拟输入数据
hidden_states = torch.randn(2, 8, 10)
hidden_states,hidden_states.shape

(tensor([[[-1.3799, -0.5041,  1.9785, -2.4707, -1.7235,  0.1333, -0.4586,
           -1.2372, -1.4359,  1.6946],
          [ 0.5212,  0.4889,  1.3202,  1.4060, -0.8607, -0.3986,  1.8616,
            1.3636,  0.2939,  2.6554],
          [ 1.4119,  0.7602,  1.2421,  0.5898,  0.5339, -0.1787,  0.6487,
            0.4778,  0.4677,  1.0863],
          [ 0.9835, -0.9382,  0.9603,  0.7203, -0.4748,  0.0652,  0.4139,
            0.6275,  0.8338,  0.8294],
          [ 0.2342, -0.3700, -0.6274, -0.8605, -0.6188, -0.7306, -1.5214,
           -0.1764,  0.2794, -0.4826],
          [ 1.0625,  1.0452,  2.0764,  0.8812,  0.6266, -0.3005, -0.1073,
           -0.0666, -0.7895, -0.1615],
          [-0.9120, -1.2686, -1.0053,  0.2372, -0.3670,  0.1405, -0.9632,
           -0.1507,  1.5099,  0.8901],
          [ 0.7716,  0.7252, -0.7744,  2.7086, -0.0482,  1.0113,  0.7917,
           -0.3397, -0.2513,  0.6066]],
 
         [[-0.6276, -1.3498, -1.0835,  0.0287,  1.4093, -1.4825, -0.2339,
            0.2222,

In [7]:
import torch.nn.init as init
import math
init.kaiming_uniform_(weight, a=math.sqrt(5))
weight,weight.shape

(Parameter containing:
 tensor([[ 0.1950, -0.3063, -0.1284,  0.2826,  0.0977, -0.2096, -0.0791,  0.0082,
          -0.2674, -0.2651],
         [-0.0143, -0.1660, -0.1692, -0.0913, -0.1949,  0.2360,  0.2252, -0.2453,
          -0.1010, -0.2708],
         [ 0.1812, -0.0692, -0.1733, -0.1500,  0.2681,  0.2262,  0.2740, -0.1827,
           0.1036,  0.1330],
         [-0.2727, -0.2496,  0.2160, -0.0819, -0.2221, -0.0938, -0.1057, -0.2661,
          -0.0144, -0.0365]], requires_grad=True),
 torch.Size([4, 10]))

In [9]:
bsz, seq_len, h = hidden_states.shape
bsz, seq_len, h

(2, 8, 10)

In [10]:
hidden_states = hidden_states.view(-1, h)
hidden_states,hidden_states.shape

(tensor([[-1.3799, -0.5041,  1.9785, -2.4707, -1.7235,  0.1333, -0.4586, -1.2372,
          -1.4359,  1.6946],
         [ 0.5212,  0.4889,  1.3202,  1.4060, -0.8607, -0.3986,  1.8616,  1.3636,
           0.2939,  2.6554],
         [ 1.4119,  0.7602,  1.2421,  0.5898,  0.5339, -0.1787,  0.6487,  0.4778,
           0.4677,  1.0863],
         [ 0.9835, -0.9382,  0.9603,  0.7203, -0.4748,  0.0652,  0.4139,  0.6275,
           0.8338,  0.8294],
         [ 0.2342, -0.3700, -0.6274, -0.8605, -0.6188, -0.7306, -1.5214, -0.1764,
           0.2794, -0.4826],
         [ 1.0625,  1.0452,  2.0764,  0.8812,  0.6266, -0.3005, -0.1073, -0.0666,
          -0.7895, -0.1615],
         [-0.9120, -1.2686, -1.0053,  0.2372, -0.3670,  0.1405, -0.9632, -0.1507,
           1.5099,  0.8901],
         [ 0.7716,  0.7252, -0.7744,  2.7086, -0.0482,  1.0113,  0.7917, -0.3397,
          -0.2513,  0.6066],
         [-0.6276, -1.3498, -1.0835,  0.0287,  1.4093, -1.4825, -0.2339,  0.2222,
          -0.2676, -0.0690],
 

In [11]:
logits = F.linear(hidden_states, weight, None)
logits, logits.shape

(tensor([[-1.3025,  0.2478, -0.4424,  1.8387],
         [-0.7395, -1.0306, -0.0555, -0.5263],
         [-0.3212, -0.8691,  0.2856, -0.6987],
         [ 0.0288, -0.3481,  0.0515, -0.0392],
         [ 0.2611, -0.0060, -0.4453,  0.3907],
         [ 0.2555, -0.6979, -0.3923, -0.2389],
         [-0.2233, -0.0967,  0.0329,  0.4847],
         [ 0.4174,  0.1232,  0.3671, -0.8764],
         [ 0.9969, -0.2723,  0.0641,  0.0696],
         [-0.6134, -0.5417, -0.0509, -0.7152],
         [-0.0943, -0.4479, -0.4106, -0.4154],
         [ 0.0703, -0.9668,  0.0997, -0.4793],
         [-0.4905, -0.1775, -0.1649, -0.0458],
         [-0.2251, -1.3737,  0.1717, -0.5099],
         [-0.2170, -0.3682, -0.2315, -0.8043],
         [ 0.0578, -0.8852, -0.5275, -0.1525]], grad_fn=<MmBackward0>),
 torch.Size([16, 4]))

In [12]:
scores = logits.softmax(dim=-1)
scores, scores.shape

(tensor([[0.0320, 0.1510, 0.0757, 0.7412],
         [0.2013, 0.1505, 0.3990, 0.2492],
         [0.2440, 0.1411, 0.4476, 0.1673],
         [0.2745, 0.1883, 0.2808, 0.2564],
         [0.2944, 0.2254, 0.1452, 0.3351],
         [0.3970, 0.1530, 0.2077, 0.2422],
         [0.1833, 0.2080, 0.2368, 0.3720],
         [0.3367, 0.2509, 0.3201, 0.0923],
         [0.4831, 0.1358, 0.1901, 0.1911],
         [0.2113, 0.2270, 0.3708, 0.1909],
         [0.3168, 0.2225, 0.2309, 0.2298],
         [0.3377, 0.1197, 0.3477, 0.1949],
         [0.1882, 0.2574, 0.2607, 0.2937],
         [0.2812, 0.0892, 0.4181, 0.2115],
         [0.2940, 0.2528, 0.2898, 0.1634],
         [0.3627, 0.1413, 0.2020, 0.2939]], grad_fn=<SoftmaxBackward0>),
 torch.Size([16, 4]))

In [14]:
topk_weight, topk_idx = torch.topk(scores, k=2, dim=-1, sorted=False)
topk_weight,topk_weight.shape, topk_idx,topk_idx.shape

(tensor([[0.7412, 0.1510],
         [0.3990, 0.2492],
         [0.4476, 0.2440],
         [0.2808, 0.2745],
         [0.3351, 0.2944],
         [0.3970, 0.2422],
         [0.3720, 0.2368],
         [0.3367, 0.3201],
         [0.4831, 0.1911],
         [0.3708, 0.2270],
         [0.3168, 0.2309],
         [0.3477, 0.3377],
         [0.2937, 0.2607],
         [0.4181, 0.2812],
         [0.2940, 0.2898],
         [0.3627, 0.2939]], grad_fn=<TopkBackward0>),
 torch.Size([16, 2]),
 tensor([[3, 1],
         [2, 3],
         [2, 0],
         [2, 0],
         [3, 0],
         [0, 3],
         [3, 2],
         [0, 2],
         [0, 3],
         [2, 1],
         [0, 2],
         [2, 0],
         [3, 2],
         [2, 0],
         [0, 2],
         [0, 3]]),
 torch.Size([16, 2]))

In [15]:
# 归一化
denominator = topk_weight.sum(dim=-1, keepdim=True) + 1e-20
denominator,denominator.shape

(tensor([[0.8922],
         [0.6482],
         [0.6916],
         [0.5553],
         [0.6294],
         [0.6392],
         [0.6087],
         [0.6568],
         [0.6742],
         [0.5979],
         [0.5477],
         [0.6854],
         [0.5543],
         [0.6993],
         [0.5838],
         [0.6567]], grad_fn=<AddBackward0>),
 torch.Size([16, 1]))

In [16]:
topk_weight = topk_weight / denominator
topk_weight, topk_weight.shape

(tensor([[0.8307, 0.1693],
         [0.6156, 0.3844],
         [0.6472, 0.3528],
         [0.5057, 0.4943],
         [0.5323, 0.4677],
         [0.6211, 0.3789],
         [0.6111, 0.3889],
         [0.5126, 0.4874],
         [0.7165, 0.2835],
         [0.6203, 0.3797],
         [0.5784, 0.4216],
         [0.5074, 0.4926],
         [0.5297, 0.4703],
         [0.5979, 0.4021],
         [0.5036, 0.4964],
         [0.5524, 0.4476]], grad_fn=<DivBackward0>),
 torch.Size([16, 2]))

In [73]:
# 训练阶段
scores_for_aux = scores
aux_topk = 2
topk_idx_for_aux_loss = topk_idx.view(bsz, -1)
topk_idx_for_aux_loss,topk_idx_for_aux_loss.shape,topk_idx,topk_idx.shape,scores_for_aux,scores_for_aux

(tensor([[3, 1, 2, 3, 2, 0, 2, 0, 3, 0, 0, 3, 3, 2, 0, 2],
         [0, 3, 2, 1, 0, 2, 2, 0, 3, 2, 2, 0, 0, 2, 0, 3]]),
 torch.Size([2, 16]),
 tensor([[3, 1],
         [2, 3],
         [2, 0],
         [2, 0],
         [3, 0],
         [0, 3],
         [3, 2],
         [0, 2],
         [0, 3],
         [2, 1],
         [0, 2],
         [2, 0],
         [3, 2],
         [2, 0],
         [0, 2],
         [0, 3]]),
 torch.Size([16, 2]),
 tensor([[0.0320, 0.1510, 0.0757, 0.7412],
         [0.2013, 0.1505, 0.3990, 0.2492],
         [0.2440, 0.1411, 0.4476, 0.1673],
         [0.2745, 0.1883, 0.2808, 0.2564],
         [0.2944, 0.2254, 0.1452, 0.3351],
         [0.3970, 0.1530, 0.2077, 0.2422],
         [0.1833, 0.2080, 0.2368, 0.3720],
         [0.3367, 0.2509, 0.3201, 0.0923],
         [0.4831, 0.1358, 0.1901, 0.1911],
         [0.2113, 0.2270, 0.3708, 0.1909],
         [0.3168, 0.2225, 0.2309, 0.2298],
         [0.3377, 0.1197, 0.3477, 0.1949],
         [0.1882, 0.2574, 0.2607, 0.2937],
   

In [19]:
scores_for_seq_aux = scores_for_aux.view(bsz, seq_len, -1)
scores_for_seq_aux,scores_for_seq_aux.shape

(tensor([[[0.0320, 0.1510, 0.0757, 0.7412],
          [0.2013, 0.1505, 0.3990, 0.2492],
          [0.2440, 0.1411, 0.4476, 0.1673],
          [0.2745, 0.1883, 0.2808, 0.2564],
          [0.2944, 0.2254, 0.1452, 0.3351],
          [0.3970, 0.1530, 0.2077, 0.2422],
          [0.1833, 0.2080, 0.2368, 0.3720],
          [0.3367, 0.2509, 0.3201, 0.0923]],
 
         [[0.4831, 0.1358, 0.1901, 0.1911],
          [0.2113, 0.2270, 0.3708, 0.1909],
          [0.3168, 0.2225, 0.2309, 0.2298],
          [0.3377, 0.1197, 0.3477, 0.1949],
          [0.1882, 0.2574, 0.2607, 0.2937],
          [0.2812, 0.0892, 0.4181, 0.2115],
          [0.2940, 0.2528, 0.2898, 0.1634],
          [0.3627, 0.1413, 0.2020, 0.2939]]], grad_fn=<ViewBackward0>),
 torch.Size([2, 8, 4]))

In [35]:
ce = torch.zeros(bsz, 4,device=hidden_states.device)
ce,ce.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([2, 4]))

In [36]:
ce.scatter_add_(1, topk_idx_for_aux_loss,
                                torch.ones(bsz, seq_len * aux_topk,device=hidden_states.device)).div_(
                    seq_len * aux_topk / 4)
ce,ce.shape

(tensor([[1.2500, 0.2500, 1.2500, 1.2500],
         [1.5000, 0.2500, 1.5000, 0.7500]]),
 torch.Size([2, 4]))

In [45]:
mean_scores = scores_for_seq_aux.mean(dim=1).detach()
mean_scores,mean_scores.shape

(tensor([[0.2454, 0.1835, 0.2641, 0.3070],
         [0.3094, 0.1807, 0.2888, 0.2211]]),
 torch.Size([2, 4]))

In [58]:
out = ce * mean_scores
out,out.shape

(tensor([[0.3068, 0.0459, 0.3302, 0.3837],
         [0.4641, 0.0452, 0.4332, 0.1659]]),
 torch.Size([2, 4]))

In [59]:
out = out.sum(dim=1)
out

tensor([1.0665, 1.1083])

In [61]:
out = out.mean()
out

tensor(1.0874)

In [62]:
topk_idx_for_aux_loss,topk_idx_for_aux_loss.shape

(tensor([[3, 1, 2, 3, 2, 0, 2, 0, 3, 0, 0, 3, 3, 2, 0, 2],
         [0, 3, 2, 1, 0, 2, 2, 0, 3, 2, 2, 0, 0, 2, 0, 3]]),
 torch.Size([2, 16]))

In [75]:
mask_ce = F.one_hot(topk_idx_for_aux_loss.view(-1), num_classes=4)
mask_ce,mask_ce.shape

(tensor([[0, 0, 0, 1],
         [0, 1, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 1],
         [0, 0, 1, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 1],
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 0, 1, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 1],
         [0, 0, 1, 0],
         [0, 1, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 1],
         [0, 0, 1, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 1]]),
 torch.Size([32, 4]))

In [76]:
ce = mask_ce.float().mean(0)
ce,ce.shape

(tensor([0.3438, 0.0625, 0.3438, 0.2500]), torch.Size([4]))

In [77]:
fi = ce * 4
fi,fi.shape

(tensor([1.3750, 0.2500, 1.3750, 1.0000]), torch.Size([4]))

tensor([[0.0320, 0.1510, 0.0757, 0.7412],
        [0.2013, 0.1505, 0.3990, 0.2492],
        [0.2440, 0.1411, 0.4476, 0.1673],
        [0.2745, 0.1883, 0.2808, 0.2564],
        [0.2944, 0.2254, 0.1452, 0.3351],
        [0.3970, 0.1530, 0.2077, 0.2422],
        [0.1833, 0.2080, 0.2368, 0.3720],
        [0.3367, 0.2509, 0.3201, 0.0923],
        [0.4831, 0.1358, 0.1901, 0.1911],
        [0.2113, 0.2270, 0.3708, 0.1909],
        [0.3168, 0.2225, 0.2309, 0.2298],
        [0.3377, 0.1197, 0.3477, 0.1949],
        [0.1882, 0.2574, 0.2607, 0.2937],
        [0.2812, 0.0892, 0.4181, 0.2115],
        [0.2940, 0.2528, 0.2898, 0.1634],
        [0.3627, 0.1413, 0.2020, 0.2939]], grad_fn=<SoftmaxBackward0>)