In [1]:
import torch

In [6]:
x = torch.randn(3, 1)
x ,x.shape

(tensor([[-0.7070],
         [ 1.2503],
         [-0.3804]]),
 torch.Size([3, 1]))

In [7]:
y = torch.randn(3, 6)
y,y.shape

(tensor([[-0.4141, -0.4823,  1.9038,  1.1020, -0.9136,  0.1858],
         [ 0.5050,  0.3583, -0.7988, -0.2876, -0.6315, -0.6089],
         [ 1.4894,  0.4866,  0.6393, -0.6706,  2.7037, -2.2715]]),
 torch.Size([3, 6]))

In [8]:
y * x

tensor([[ 0.2928,  0.3410, -1.3460, -0.7791,  0.6459, -0.1313],
        [ 0.6314,  0.4480, -0.9987, -0.3596, -0.7896, -0.7613],
        [-0.5666, -0.1851, -0.2432,  0.2551, -1.0285,  0.8640]])