In [7]:
import torch
import torch.nn as nn

In [8]:
# 创建一个全连接层
linear = nn.Linear(5, 3)
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[ 0.0946, -0.0374, -0.1589, -0.3093, -0.0812],
        [ 0.1635, -0.4408,  0.0441,  0.2878,  0.2440],
        [ 0.0089, -0.4220, -0.0163, -0.0329, -0.2380]], requires_grad=True)
Parameter containing:
tensor([-0.2167,  0.3579, -0.3253], requires_grad=True)


In [9]:
# 常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [10]:
nn.init.ones_(linear.weight)
print(linear.weight)
nn.init.constant_(linear.bias, 10)
print(linear.bias)

Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)
Parameter containing:
tensor([10., 10., 10.], requires_grad=True)


In [11]:
# 秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]], requires_grad=True)


In [12]:
# 均匀分布初始化
nn.init.uniform_(linear.weight,1,10)
print(linear.weight)

Parameter containing:
tensor([[4.6065, 1.1922, 2.9914, 6.5495, 7.7298],
        [9.7590, 1.0824, 2.6063, 7.1073, 3.3291],
        [3.3163, 2.5998, 7.4129, 6.4681, 4.5870]], requires_grad=True)


In [15]:
# 正态分布初始化
nn.init.normal_(linear.weight,0,1)
print(linear.weight)

Parameter containing:
tensor([[ 0.4402, -1.6226, -1.8237,  0.3244,  1.9876],
        [ 0.1010,  1.0487,  0.0201, -0.7183, -0.2411],
        [ 1.5307, -1.6687,  0.8002,  0.3808, -0.9955]], requires_grad=True)


In [18]:
# Xavier初始化,sigmoid,tanh
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.0042,  0.8244, -0.7749, -0.4626,  0.2141],
        [ 0.3398,  0.0605,  0.2337,  0.2229, -0.2162],
        [ 0.0174, -0.1853, -0.3792, -0.8420,  0.0477]], requires_grad=True)
Parameter containing:
tensor([[-0.2568, -1.7612,  0.9393,  0.0223, -0.4874],
        [ 0.1219, -0.0469,  0.1323,  0.3556, -0.2878],
        [-0.2045, -0.1441,  0.2915,  0.0393, -0.2106]], requires_grad=True)


In [21]:
# He初始化
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.8745, -0.5387, -0.0124, -0.3493, -0.3877],
        [-0.6336,  0.6090,  0.5066, -0.9484, -0.7688],
        [-0.4397, -0.6047, -0.5716, -0.0766,  0.2943]], requires_grad=True)
Parameter containing:
tensor([[-0.4472,  0.4417,  0.1503, -0.0649, -0.7737],
        [ 0.3261, -0.0376,  1.0120,  0.2850,  0.2270],
        [-0.7350, -0.5819,  0.2944, -0.0222,  0.3700]], requires_grad=True)
